# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Create and set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy all application source code to the working directory
COPY . .

# Expose the port that the application will run on (3000 by default)
EXPOSE 3000

# Define the command to run your application
CMD ["node", "index.js"]